name: Build

on: [push, pull_request]

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v4
      with:
        go-version: '1.13'
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Test
      run: |
        go mod tidy -v
        go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Build
      run: go build ./...
